language: android
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.2

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;24.0.3"
  - chmod +x gradlew

script:
  - "./gradlew clean build"
  - "./gradlew :coroutines:clean :coroutines:build :coroutines:publish"
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew clean :coroutines:bintrayUpload; fi
  - "./gradlew :livedata:clean :livedata:build :livedata:publish"
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew clean :livedata:bintrayUpload; fi
  - "./gradlew :logger:clean :logger:build :logger:publish"
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew clean :logger:bintrayUpload; fi