name: Publish to bintray

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cleaning
        run: ./gradlew clean build clean
      - name: Tests
        run: ./gradlew test
      - name: Publish livedata
        env:
          bintrayUser: ${{ secrets.bintray_user }}
          bintrayApiKey: ${{ secrets.bintray_apikey }}
        run: ./gradlew :livedata:bintrayUpload